package com.wallora.app.domain.model

/**
 * Curated wallpaper categories. Each category maps to source-specific queries/subreddits.
 *
 * [pexelsQuery] — search term for Pexels curated endpoint.
 * [wallhavenQuery] — additional query for Wallhaven.
 * [wallhavenCategories] — Wallhaven categories bitmask string (general=100, anime=010, people=001).
 * [subreddits] — list of SFW wallpaper subreddits for Reddit.
 * [unsplashQuery] — search term for Unsplash.
 * [pixabayQuery] — search term for Pixabay.
 * [openverseQuery] — search term for Openverse (Creative Commons).
 * [nasaQuery] — search term for NASA Image Library.
 * [flickrQuery] — search term for Flickr (CC-licensed, safe-search).
 * [wikimediaQuery] — search term for Wikimedia Commons File namespace.
 */
enum class Category(
    val displayName: String,
    val pexelsQuery: String,
    val wallhavenQuery: String,
    val wallhavenCategories: String = "111", // general+anime+people
    val subreddits: List<String>,
    val unsplashQuery: String,
    val pixabayQuery: String,
    val openverseQuery: String,
    val nasaQuery: String,
    val flickrQuery: String,
    val wikimediaQuery: String,
) {
    // ---- Vibrant / high-saturation leads — shown first in the chip row ----
    VIBRANT(
        displayName = "Vibrant",
        pexelsQuery = "vibrant colorful wallpaper",
        wallhavenQuery = "colorful vibrant",
        wallhavenCategories = "100",
        subreddits = listOf("wallpaper", "wallpapers"),
        unsplashQuery = "vibrant colorful",
        pixabayQuery = "vibrant colorful",
        openverseQuery = "vibrant colorful",
        nasaQuery = "aurora borealis lights",
        flickrQuery = "vibrant colorful wallpaper",
        wikimediaQuery = "colorful vibrant",
    ),
    ABSTRACT(
        displayName = "Abstract",
        pexelsQuery = "abstract colorful",
        wallhavenQuery = "abstract",
        subreddits = listOf("wallpaper", "wallpapers"),
        unsplashQuery = "abstract",
        pixabayQuery = "abstract colorful",
        openverseQuery = "abstract art background",
        nasaQuery = "nebula abstract colorful",
        flickrQuery = "abstract art",
        wikimediaQuery = "abstract art",
    ),
    NEON(
        displayName = "Neon",
        pexelsQuery = "neon lights glow",
        wallhavenQuery = "neon",
        wallhavenCategories = "100",
        subreddits = listOf("Cyberpunk", "outrun"),
        unsplashQuery = "neon",
        pixabayQuery = "neon",
        openverseQuery = "neon lights glow",
        nasaQuery = "aurora lights glow",
        flickrQuery = "neon lights",
        wikimediaQuery = "neon",
    ),
    GRADIENT(
        displayName = "Gradient",
        pexelsQuery = "gradient colorful background",
        wallhavenQuery = "gradient",
        wallhavenCategories = "100",
        subreddits = listOf("wallpaper", "wallpapers"),
        unsplashQuery = "gradient",
        pixabayQuery = "gradient",
        openverseQuery = "gradient color background",
        nasaQuery = "nebula gradient color",
        flickrQuery = "gradient color background",
        wikimediaQuery = "gradient",
    ),
    SPACE(
        displayName = "Space",
        pexelsQuery = "space galaxy nebula",
        wallhavenQuery = "space galaxy",
        subreddits = listOf("spaceporn", "astrophotography"),
        unsplashQuery = "space galaxy",
        pixabayQuery = "space galaxy nebula",
        openverseQuery = "space galaxy nebula",
        nasaQuery = "galaxy nebula space",
        flickrQuery = "space galaxy nebula",
        wikimediaQuery = "galaxy nebula space",
    ),
    AI_ART(
        displayName = "AI Art",
        pexelsQuery = "digital art vibrant colorful",
        wallhavenQuery = "digital art illustration",
        subreddits = listOf("AIArt", "midjourney", "StableDiffusion"),
        unsplashQuery = "digital art colorful",
        pixabayQuery = "digital art colorful",
        openverseQuery = "digital art illustration",
        nasaQuery = "nebula art colorful",
        flickrQuery = "digital art illustration",
        wikimediaQuery = "digital art",
    ),
    // ---- Topical / subject categories ----
    NATURE(
        displayName = "Nature",
        pexelsQuery = "nature landscape",
        wallhavenQuery = "nature",
        wallhavenCategories = "100",
        subreddits = listOf("EarthPorn", "NatureIsFuckingLit"),
        unsplashQuery = "nature",
        pixabayQuery = "nature landscape",
        openverseQuery = "nature landscape",
        nasaQuery = "earth nature from space",
        flickrQuery = "nature landscape",
        wikimediaQuery = "nature landscape",
    ),
    LANDSCAPES(
        displayName = "Landscapes",
        pexelsQuery = "landscape scenery",
        wallhavenQuery = "landscape",
        subreddits = listOf("EarthPorn", "LandscapePhotography"),
        unsplashQuery = "landscape",
        pixabayQuery = "landscape scenery",
        openverseQuery = "landscape scenery",
        nasaQuery = "earth landscape aerial",
        flickrQuery = "landscape scenic",
        wikimediaQuery = "landscape",
    ),
    CITY(
        displayName = "City",
        pexelsQuery = "city urban skyline",
        wallhavenQuery = "cityscape",
        subreddits = listOf("CityPorn", "urbanporn"),
        unsplashQuery = "cityscape",
        pixabayQuery = "city skyline",
        openverseQuery = "cityscape urban skyline",
        nasaQuery = "earth city lights night",
        flickrQuery = "city skyline",
        wikimediaQuery = "cityscape",
    ),
    ARCHITECTURE(
        displayName = "Architecture",
        pexelsQuery = "architecture building",
        wallhavenQuery = "architecture",
        subreddits = listOf("ArchitecturePorn", "wallpaper"),
        unsplashQuery = "architecture",
        pixabayQuery = "architecture",
        openverseQuery = "architecture building",
        nasaQuery = "space station architecture",
        flickrQuery = "architecture building",
        wikimediaQuery = "architecture",
    ),
    ANIMALS(
        displayName = "Animals",
        pexelsQuery = "animals wildlife",
        wallhavenQuery = "animals wildlife",
        subreddits = listOf("NatureIsFuckingLit", "wildlifephotography"),
        unsplashQuery = "animals wildlife",
        pixabayQuery = "animals wildlife",
        openverseQuery = "animals wildlife",
        nasaQuery = "earth wildlife animals",
        flickrQuery = "animals wildlife",
        wikimediaQuery = "wildlife animals",
    ),
    CARS(
        displayName = "Cars",
        pexelsQuery = "cars automotive",
        wallhavenQuery = "cars automotive",
        subreddits = listOf("carporn", "wallpaper"),
        unsplashQuery = "cars automotive",
        pixabayQuery = "cars automotive",
        openverseQuery = "cars automobile",
        nasaQuery = "rover vehicle spacecraft",
        flickrQuery = "cars automotive",
        wikimediaQuery = "automobile car",
    ),
    ANIME(
        displayName = "Anime",
        pexelsQuery = "anime illustration",
        wallhavenQuery = "anime",
        wallhavenCategories = "010",
        subreddits = listOf("Animewallpaper", "Amoledbackgrounds"),
        unsplashQuery = "anime illustration",
        pixabayQuery = "anime",
        openverseQuery = "anime illustration",
        nasaQuery = "nebula colorful art",
        flickrQuery = "anime illustration",
        wikimediaQuery = "anime",
    ),
    ART(
        displayName = "Art",
        pexelsQuery = "digital art illustration",
        wallhavenQuery = "art",
        subreddits = listOf("ImaginaryLandscapes", "SpecArt"),
        unsplashQuery = "art illustration",
        pixabayQuery = "art illustration",
        openverseQuery = "art painting illustration",
        nasaQuery = "nebula art",
        flickrQuery = "art painting",
        wikimediaQuery = "painting art masterpiece",
    ),
    TECHNOLOGY(
        displayName = "Technology",
        pexelsQuery = "technology abstract digital",
        wallhavenQuery = "technology",
        subreddits = listOf("wallpaper", "wallpapers"),
        unsplashQuery = "technology",
        pixabayQuery = "technology",
        openverseQuery = "technology digital",
        nasaQuery = "spacecraft technology engineering",
        flickrQuery = "technology futuristic",
        wikimediaQuery = "technology",
    ),
    // ---- Muted / dark — kept but moved to end so they don't dominate the default view ----
    MINIMAL(
        displayName = "Minimal",
        pexelsQuery = "minimal simple clean",
        wallhavenQuery = "minimalist",
        subreddits = listOf("MinimalWallpaper", "Minimalism"),
        unsplashQuery = "minimal",
        pixabayQuery = "minimal",
        openverseQuery = "minimal simple clean",
        nasaQuery = "earth minimal",
        flickrQuery = "minimalist simple",
        wikimediaQuery = "minimalist",
    ),
    AMOLED(
        displayName = "Dark/AMOLED",
        pexelsQuery = "dark black amoled",
        wallhavenQuery = "dark black",
        subreddits = listOf("Amoledbackgrounds", "darkwallpaper"),
        unsplashQuery = "dark minimal",
        pixabayQuery = "dark amoled",
        openverseQuery = "dark black",
        nasaQuery = "space dark",
        flickrQuery = "dark black abstract",
        wikimediaQuery = "dark",
    ),
}
